source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

pod 'DTCoreText'
pod 'GRMustache'
pod 'GPUImage'
pod 'MBProgressHUD'
pod 'ReactiveCocoa'
pod 'SDWebImage'
pod 'TBXML'
pod 'TOWebViewController'
pod 'TTTAttributedLabel'
pod 'TPKeyboardAvoiding'
pod 'Masonry'
pod 'MJRefresh'
pod 'NYXImagesKit', '2.3'
pod 'JazzHands', '2.0.0'
pod 'CTAssetsPickerController'
pod 'PureLayout'
pod 'JCSegmentBarController'
pod 'pop'
pod 'AFNetworking','2.6.3'
pod 'AMap2DMap'
pod 'AMapSearch'
pod 'UMengSocial'
pod 'JCSegmentBarController'
pod 'Pingpp'
